### ISSUE TITLE
consider making piscem a dependency in the simpleaf conda env

### ISSUE THREAD

**Issue by rpolicastro** [COMBINE-lab/simpleaf#118]
Hello!

I was wondering if you would consider adding piscem as a dependency for simpleaf on conda.

When building pipelines it's convenient to use the conda-associated docker containers on biocontainers. Since piscem isn't a dependency for simpleaf I currently need to make a custom docker image to add it.

Cheers,
Bob

**Comment by rob-p** [comment]
Great, thanks! A new piscem release (with decoy support and some other improvements) is imminent. We'll try this out when we push that release!

--Rob

**Comment by rob-p** [comment]
Should be done!
