### ISSUE TITLE
0 cells returned

### ISSUE THREAD

**Issue by mousepixels** [COMBINE-lab/simpleaf#132]
Hi! I have used simpleaf several times in the past and have had great results.

However, I am currently having an issue where the pipeline runs fine (no errors, mapping rate >80%, etc) but there are 0 cells output. 

It is simple 10xv3 chemistry. I have double-checked the chemistry and verified by running through CellRanger, which returns ~10k cells). I have used this same installation of simpleaf and the same index before successfully.

Any advice for quick troubleshooting?

version: simpleaf 0.15.1

My command:

```
simpleaf quant \ 
--reads1 <path>/S1_L001_R1_001.fastq.gz,<path>/S1_L001_R1_002.fastq.gz,<path>/S1_L002_R1_001.fastq.gz,<path>/S1_L002_R1_002.fastq.gz,<path>/S1_L003_R1_001.fastq.gz,<path>/S1_L003_R1_002.fastq.gz,<path>/S1_L004_R1_001.fastq.gz,<path>/S1_L004_R1_002.fastq.gz \
--reads2 <path>/S1_L001_R2_001.fastq.gz,<path>/S1_L001_R2_002.fastq.gz,<path>/S1_L002_R2_001.fastq.gz,<path>/S1_L002_R2_002.fastq.gz,<path>/S1_L003_R2_001.fastq.gz,<path>/S1_L003_R2_002.fastq.gz,<path>/S1_L004_R2_001.fastq.gz,<path>/S1_L004_R2_002.fastq.gz \
--threads 42 \
--index <path>/index/ \
--chemistry 10xv3 \
--resolution cr-like \
--unfiltered-pl \
--expected-ori fw \
--output simpleaf_output/6289_MW_0183
```

snippet from map_info:

```
    "num_mapped": 276424581,
    "num_poisoned": 0,
    "num_reads": 329332747,
    "percent_mapped": 83.93473880688822,
    "runtime_seconds": 1557.0
```    
    
 quant.json:
```
 {
  "alt_resolved_cell_numbers": [],
  "cmd": "<path>/alevin-fry quant -i simpleaf_output/6289_MW_0195/af_quant -o simpleaf_output/6289_MW_0195/af_quant -t 42 -m <path>/simpleaf_90/index/t2g_3col.tsv -r cr-like",
  "dump_eq": false,
  "empty_resolved_cell_numbers": [],
  "num_genes": 4363824, (yes number is large but I've used index before)
  "num_quantified_cells": 0,
  "quant_options": {
    "cmdline": "<path>/alevin-fry quant -i simpleaf_output/6289_MW_0195/af_quant -o simpleaf_output/6289_MW_0195/af_quant -t 42 -m <path>/simpleaf_90/index/t2g_3col.tsv -r cr-like",
    "dump_eq": false,
    "filter_list": null,
    "init_uniform": false,
    "input_dir": "simpleaf_output/6289_MW_0195/af_quant",
    "large_graph_thresh": 0,
    "num_bootstraps": 0,
    "num_threads": 42,
    "output_dir": "simpleaf_output/6289_MW_0195/af_quant",
    "pug_exact_umi": false,
    "resolution": "CellRangerLike",
    "sa_model": "WinnerTakeAll",
    "small_thresh": 10,
    "summary_stat": false,
    "tg_map": "/<path>/simpleaf_90/index/t2g_3col.tsv",
    "use_mtx": true,
    "version": "0.8.2"
  },
  "resolution_strategy": "CellRangerLike",
  "usa_mode": true,
  "version_str": "0.8.2"
```

**Comment by rob-p** [comment]
Hi @mousepixels,

  Thanks for the details.  One question I might ask is, can you please verify that the 10x v3 permit list in your `$ALEVIN_FRY_HOME` looks correct?  We recently had the default link where that file was being stored go stale, and we had to refresh it.  You can either download and unpack the file manually in the proper location, or update to the latest `simpleaf` to have automatic download capability fixed.  We've added a level of indirection for the future, so if the URL ever has to change again, we can modify it without requiring an update to `simpleaf` itself, but for the most recent case, I think you'll have to either update `simpleaf` (which should be simple — pun intended), or manually download or point at the v3 permit list.

--Rob

**Comment by mousepixels** [comment]
Ahhh ty ty ty. I had to update and delete the old plist for it to fetch it. Nice easy fix! Just wish I noticed before processing 142 samples. Thanks Rob!

**Comment by mousepixels** [comment]
Also, I really appreciate how you respond to GitHub issues faster than most people respond to text messages xD

**Comment by rob-p** [comment]
Great; glad it was an easy fix. Sorry to hear you burned cycles on a bunch of samples, but hopefully rerunning is quick!
