### ISSUE TITLE
read lengths differ

### ISSUE THREAD

**Issue by robertzeibich** [COMBINE-lab/simpleaf#162]
R1 27; R2 125
R1 29; R2 99
R1 29; R2 92

Alignment crashes when the read length is less than 31.

> [2024-10-19 14:41:05.213] [info] enable structural constraints : false
> [2024-10-19 14:41:05.213] [info] No poison k-mer map exists, or it was requested not to be used
> [2024-10-19 14:41:05.213] [info] loading index from /scratch/xm41/hg38_resources/scRNA/refdata-gex-GRCh38-2020-A/human-2020-A_splici/91/index/piscem_idx
> [2024-10-19 14:41:08.690] [info] done loading index
> Error: piscem mapping failed with exit status ExitStatus(unix_wait_status(134))

Should I create an index with `simpleaf index -k 26`?

**Comment by rob-p** [comment]
Can you please say how you are running simpleaf (the invocation) and also what versions of simpleaf, piscem and alevin-fry you are using?  R1 is usually the technical read and only needs to be long enough to hold the barcode and UMI. Most commonly, it’s not even attempted to align it. Regardless, in the worst case reads shorter than the kmer length should be discarded ( not cause termination ). You shouldn’t have to change the index. 

—Rob

**Comment by robertzeibich** [comment]
I highly appreciate your quick response.
I am following the simpleaf [online documentation](https://combine-lab.github.io/alevin-fry-tutorials/2023/simpleaf-piscem/).

That's how I created the index:

```
rlen=91
IDX_DIR="${REF_DIR}/human-2020-A_splici/${rlen}"
```


```
 simpleaf index \
--output $IDX_DIR \
--fasta $REF_DIR/fasta/genome.fa \
--gtf $REF_DIR/genes/genes.gtf \
--rlen ${rlen} \
--threads $(nproc) \
--use-piscem
```

```
simpleaf quant \
--reads1 ${workdir}/${sra_id}_1.fastq.gz \
--reads2 ${workdir}/${sra_id}_2.fastq.gz \
--threads $(nproc) \
--index $IDX_DIR/index \
--chemistry 10xv3 --resolution cr-like \
--expected-ori fw --unfiltered-pl \
--t2g-map $IDX_DIR/index/t2g_3col.tsv \
--output ${workdir}/alevin/${sra_id}
```

**Comment by rob-p** [comment]
Hrmm, certainly it should not be the case that read 1 is being mapped in 10xv3 chemistry. You more that this happens when read 1 is < 31 nucleotides. Do you have data with longer R1 where it runs to completion?

If it is possible to share your index somehow, and a small sample of reads that reproduce the problem (a few hundred or few thousand should suffice), we’d be happy to take a look.

**Comment by robertzeibich** [comment]
Sure. I am happy to. Where should I send the files to?

**Comment by rob-p** [comment]
Hi @robertzeibich,

  The read pairs (when gzipped) should be small enough to upload directly here. If you send me an e-mail (rob@cs.umd.edu), I can share a `box` folder with you where you can upload the index.

--Rob

**Comment by robertzeibich** [comment]
I selected the first 5,000 rows:

[SRR12905322_1.fastq_sub.gz](https://github.com/user-attachments/files/17442724/SRR12905322_1.fastq_sub.gz)
[SRR12905322_2.fastq_sub.gz](https://github.com/user-attachments/files/17442726/SRR12905322_2.fastq_sub.gz)

I hope that this is enough. I will upload the index in a second.

**Comment by robertzeibich** [comment]
Based on your question: Do you have data with longer R1 where it runs to completion? Yes, I have longer R1 where it runs to completion.

**Comment by robertzeibich** [comment]
This issue can be closed due to @rob-p support. 

If you should run into the same error (see first message), make sure that the FASTQ files were downloaded correctly. 

Re different read lenght: 

> "R1 is usually the technical read and only needs to be long enough to hold the barcode and UMI" 
> R2 contains the sequence. From a given sequence the length can be extracted. 

As I stated in my first message, I got read lengths of 

R1 27; R2 125
R1 29; R2 99
R1 29; R2 92

At the end, I used the read lengths 98 and 91 to build the indices. However, I also tried 99 and 92 and the number of cells and genes were exactly the same.
