### ISSUE TITLE
libgcc-ng >=12 needed for installation

### ISSUE THREAD

**Issue by chjp** [COMBINE-lab/simpleaf#42]
conda installation returns error:
nothing provides libgcc-ng >=12 needed by simpleaf-0.2.1-h9f5acd7_0

**Comment by rob-p** [comment]
Perhaps try adding Conda-forge to your list of channels, they seem to have a sufficient version [here](https://anaconda.org/conda-forge/libgcc-ng).

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
```

**Comment by chjp** [comment]
`conda config --add channels conda-forge
` works. Thanks.
